# Generated by Django 5.0.7 on 2024-11-09 18:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='///', max_length=230, unique=True, verbose_name='Название функции')),
                ('path', models.TextField(default='///', verbose_name='Путь')),
                ('error', models.TextField(default='///', verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
        ),
    ]
