# Generated by Django 5.0.7 on 2024-11-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errordata',
            name='name',
            field=models.CharField(default='///', max_length=230, verbose_name='Название функции'),
        ),
    ]
