# Generated by Django 5.0.7 on 2024-08-24 07:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя')),
                ('file', models.FileField(upload_to='files/', verbose_name='Файл')),
            ],
        ),
        migrations.AlterModelOptions(
            name='groupproductdkcmagadel',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='magadel',
            options={'verbose_name': 'Магадель', 'verbose_name_plural': 'Магадель'},
        ),
        migrations.AlterModelOptions(
            name='productdkcmagadel',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='magadel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='magadel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='productdkcmagadel',
            name='free_balance',
            field=models.FloatField(blank=True, null=True, verbose_name='Свободный остаток'),
        ),
        migrations.AddField(
            model_name='productdkcmagadel',
            name='list_possible_deliveries',
            field=models.TextField(blank=True, null=True, verbose_name='Даты возможных поставок'),
        ),
        migrations.AddField(
            model_name='productdkcmagadel',
            name='price',
            field=models.FloatField(default=0, verbose_name='Прайс'),
        ),
        migrations.AddField(
            model_name='productdkcmagadel',
            name='sum_possible_deliveries',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма возможных поставок'),
        ),
        migrations.AddField(
            model_name='productdkcmagadel',
            name='unit',
            field=models.CharField(blank=True, default='Не указано', max_length=300, null=True, verbose_name='ЕдИзм'),
        ),
    ]
