# Generated by Django 5.0.7 on 2024-08-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdkcmagadel',
            name='free_balance',
            field=models.FloatField(blank=True, null=True, verbose_name='Свободный остаток'),
        ),
        migrations.AddField(
            model_name='productdkcmagadel',
            name='list_possible_deliveries',
            field=models.TextField(blank=True, null=True, verbose_name='Даты возможных поставок'),
        ),
        migrations.AddField(
            model_name='productdkcmagadel',
            name='sum_possible_deliveries',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма возможных поставок'),
        ),
    ]
