# Generated by Django 5.0.7 on 2024-08-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_productdkcmagadel_free_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdkcmagadel',
            name='unit',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ЕдИзм'),
        ),
    ]
