# Generated by Django 5.0.7 on 2024-08-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_productdkcmagadel_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdkcmagadel',
            name='unit',
            field=models.CharField(blank=True, default='Не указано', max_length=300, null=True, verbose_name='ЕдИзм'),
        ),
    ]
