# Generated by Django 5.0.7 on 2024-08-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_magadel_created_at_magadel_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupproductdkcmagadel',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='magadel',
            options={'verbose_name': 'Магадель', 'verbose_name_plural': 'Магадель'},
        ),
        migrations.AlterModelOptions(
            name='productdkcmagadel',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='productdkcmagadel',
            name='price',
            field=models.FloatField(default=0, verbose_name='Прайс'),
        ),
    ]
