# Generated by Django 5.0.7 on 2024-10-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaek', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='art',
            field=models.TextField(default='Не указан', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(),
        ),
    ]
