# Generated by Django 5.0.7 on 2024-12-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaek', '0002_classificationpriceproduct_instruction_volumelevel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volumelevel',
            name='value',
        ),
        migrations.AddField(
            model_name='volumelevel',
            name='start_value',
            field=models.FloatField(default=0, unique=True, verbose_name='От'),
        ),
        migrations.AddField(
            model_name='volumelevel',
            name='stop_value',
            field=models.FloatField(default=0, unique=True, verbose_name='До'),
        ),
    ]
