# Generated by Django 5.0.7 on 2024-12-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaek', '0003_remove_volumelevel_value_volumelevel_start_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classificationpriceproduct',
            options={'verbose_name': 'Ценовая категория', 'verbose_name_plural': '2.1 Ценовые категории'},
        ),
        migrations.AlterModelOptions(
            name='clientclassificationdiscount',
            options={'verbose_name': 'Скидки типов клиентов', 'verbose_name_plural': '3.1 Скидка типа клиента'},
        ),
        migrations.AlterModelOptions(
            name='typeclient',
            options={'verbose_name': 'Тип клиента', 'verbose_name_plural': '1.1 Типы клиентов'},
        ),
        migrations.AlterModelOptions(
            name='volumeatdiscount',
            options={'verbose_name': 'Скидка за объем', 'verbose_name_plural': '3.2 Скидки за объем'},
        ),
        migrations.AlterModelOptions(
            name='volumelevel',
            options={'verbose_name': 'Градация объема', 'verbose_name_plural': '4.1 Градации объемов'},
        ),
        migrations.AddField(
            model_name='typeclient',
            name='color',
            field=models.CharField(default='d6e1c2', max_length=20, verbose_name='Цвет'),
        ),
    ]
