# Generated by Django 5.0.7 on 2024-10-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaek', '0003_product_nomenclature_group_product_packaging_norm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
