# Generated by Django 5.0.7 on 2024-10-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaek', '0004_product_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Объем куб.м'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Вес (кг)'),
        ),
    ]
