# Generated by Django 5.0.7 on 2025-01-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaek', '0005_remove_volumeatdiscount_unique_type_client_volume_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volumelevel',
            name='stop_value',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='До'),
        ),
    ]
