# Generated by Django 5.0.7 on 2024-10-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaek', '0005_alter_product_volume_alter_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Объем куб.м'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Вес (кг)'),
        ),
    ]
