# Generated by Django 5.0.7 on 2024-11-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaek', '0007_zaekprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='classification',
            field=models.CharField(blank=True, default='Нет данных', max_length=100, null=True, verbose_name='Классификация ПП'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_group_2',
            field=models.CharField(blank=True, default='Нет данных', max_length=100, null=True, verbose_name='Ценовая группа'),
        ),
        migrations.AddField(
            model_name='product',
            name='summary_price_group',
            field=models.CharField(blank=True, default='Нет данных', max_length=100, null=True, verbose_name='Ценовая группа сводная'),
        ),
    ]
