# Generated by Django 5.0.7 on 2024-11-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaek', '0008_product_classification_product_price_group_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Нет данных', verbose_name='Номенклатура'),
        ),
    ]
