# Generated by Django 5.0.7 on 2024-11-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaek', '0009_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='art',
            field=models.CharField(default='Нет данных', max_length=100, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(default='Нет данных', verbose_name='Номенклатура'),
        ),
    ]
