# Generated by Django 5.0.7 on 2024-11-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaek', '0010_alter_product_art_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_group_list',
            field=models.TextField(default='Нет данных', verbose_name='Список групп'),
        ),
    ]
