# Generated by Django 5.0.7 on 2024-11-08 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaek', '0011_product_price_group_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_group',
        ),
        migrations.DeleteModel(
            name='PriceGroup',
        ),
    ]
