# Generated by Django 5.0.7 on 2024-11-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaek', '0012_remove_product_price_group_delete_pricegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaekprice',
            name='name',
            field=models.CharField(default='Прайс', max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
